### PR TITLE
Added basic validation to new test order screen. #1908

### PR DESCRIPTION
**Pull request by DaveBlueFrontier**

### CODE REVIEW

**Comment by tripledub** [comment]
Not sure it's a good idea to validate only on the client side, does this have server side validation as a fall back if someone turns of javascript or messes in the console for example?

**Comment by DaveBlueFrontier** [comment]
We have to assume that the people who are using this will probably not be trying to hack the system.  If they have JS turned off then much of the site will not work (ReactJS for example).  Server level validation is a good idea as a fallback, but some level of immediate information is probably more what is required here.

**Comment by tripledub** [comment]
You can't really assume anything in my experience. This really needs server side validation and any javascript validation should really use and Ajax call to the server and base it's validation on any errors that are passed back. Not really sure why we are using a javascript form here in the first place, we seem to have gone React.js obsessed when often there is no real use case for it. Any JS thing must be done to improve the user experience not to avoid writing server side code.

**Comment by tripledub** [comment]
@DaveBlueFrontier Don't take the above comments personally, there seems to be a lot of bad practice inherited from previous abuse of React.js being over-used and I'm going to raise a ticket to look into the impact this has (plan.io seems to be playing games this morning). I'll merge this for the time being as client side validation is progress at least but please be mindful of the earlier remarks - it's never an acceptable substitute for server side validation either. Ideally this goes beyond things like rails and in a perfect world you'd enforce validation on the database layer - assuming you were using a proper DB of course such as Postgres.
@jorgegorka @cisaacs01 @anthonyoleary

**Pull request merged**
