### PR TITLE
Fixup auto gen patient

### PR DESCRIPTION
**Pull request by DaveFIND**

### CODE REVIEW

**Comment by jorgegorka** [comment]
In my opinion the right way to do this task is to override this method:
    def validate_name_and_entity_id

in the Vietnam engine and not validate entity_id there.  If you do that you don't need to change anything else in the core engine (the form, the tests...) they can remain as they were originally.

**Comment by jackregnart** [comment]
There's no point making `core` and `vn` work differently in this case.  You don't need to validate `entity_id` in either place, so why do it? As far as everybody seems to be concerned `entity_id` is irrelevant.

**Comment by jorgegorka** [comment]
Good to hear that is not needed.  One less thing to care about .

**Comment by jackregnart** [comment]
Re-think needed.

**Pull request closed without merging**
