### PR TITLE
Add institute dropdown

### PR DESCRIPTION
**Pull request by minhnghivn**

### CODE REVIEW

**Comment by jackregnart** [comment]
The reason the original PR was closed was because there was no validation.

Please add validation to the model, and fix appropriate tests.

**Comment by minhnghivn** [comment]
our mistake, the branch is not yet ready for a pull

**Comment by jackregnart** [comment]
It's better to leave these PR's open and add a 'do not merge' tag.

**Comment by minhnghivn** [comment]
yes, thank you Jack for the suggestion

**Pull request closed without merging**
